apiVersion: v1
kind: Service
metadata:
  # URL: http://qwen3p5-4b-worker-service.oss-models.svc.cluster.local:30000/v1
  name: qwen3p5-4b-worker-service
  namespace: oss-models
spec:
  selector:
    app: qwen3p5-4b-worker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qwen3p5-4b-worker
  namespace: oss-models
spec:
  serviceName: qwen3p5-4b-worker
  selector:
    matchLabels:
      app: qwen3p5-4b-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: qwen3p5-4b-worker
    spec:
      hostIPC: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.azure.com/agentpool: a100pool
        # kubectl label node <node-name> dedicated=sglang --overwrite
        dedicated: sglang
      tolerations:
        - key: "sku"
          operator: "Equal"
          value: "a100pool"
          effect: "NoSchedule"
      # hostNetwork: true
      dnsPolicy: ClusterFirst
      containers:
        - name: worker-container
          # ref: https://hub.docker.com/r/lmsysorg/sglang/tags
          image: lmsysorg/sglang:nightly-dev-20260429-14b4e6fa
          env:
            # https://github.com/Azure/AKS/issues/3680
            - name: PASS_DEVICE_SPECS
              value: "true"
            - name: HF_HOME
              value: /mnt/local/hf_cache
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            # full script to run
            - |
              # service launch
              rm -rf /mnt/local/log/qwen3p5-4b/
              mkdir -p  /mnt/local/log/qwen3p5-4b/requests
              # pip install -U huggingface_hub
              # kubectl cp ./fastcontext_sft_qwen3.5_4b_hf_iter_0000137 pod-name:/mnt/local/models
              echo "==== start sglang server ===="
              python3 -m sglang.launch_server \
                --model-path /mnt/local/models/fastcontext_sft_qwen3.5_4b_hf_iter_0000137 \
                --served-model-name qwen3p5-4b \
                --reasoning-parser qwen3 \
                --tool-call-parser qwen3_coder \
                --context-length 262144 \
                --trust-remote-code \
                --dtype bfloat16 \
                --host 0.0.0.0 \
                --port 30000 \
                --tp-size 1 \
                --mem-fraction-static 0.8 \
                --log-requests \
                --log-requests-format json \
                --log-requests-target stdout /mnt/local/log/qwen3p5-4b/requests \
                --log-requests-level 3 2>&1 | tee /mnt/local/log/qwen3p5-4b/log.txt
              tail -f /dev/null # keep container alive for debugging
          ports:
            - containerPort: 30000
            - containerPort: 20000
          volumeMounts:
            - name: local-mnt
              mountPath: /mnt/local
            - name: localtime
              mountPath: /etc/localtime
            - name: dshm
              mountPath: /dev/shm

          resources:
            limits:
              cpu: "8"
              memory: 96Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "8"
              memory: 96Gi
              nvidia.com/gpu: "1"
      volumes:
        - name: local-mnt
          hostPath:
            path: /mnt/local
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 64Gi
